"""
@file
@brief Structured command schema and validation for SmartEdit SLM Assistant.
@author SmartEdit Team
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
import json
import logging

logger = logging.getLogger(__name__)


class ActionType:
    REMOVE_SILENCE = "remove_silence"
    ARRANGE_CLIPS = "arrange_clips"
    DETECT_SHAKY = "detect_shaky"
    LABEL_SHAKY = "label_shaky"
    ROUGH_CUT = "rough_cut"
    DELETE_SHAKY = "delete_shaky"
    REMOVE_SHAKY = "delete_shaky"  # Alias for delete_shaky
    TRIM_TO_DURATION = "trim_to_duration"

    ALL_ACTIONS = {
        REMOVE_SILENCE,
        ARRANGE_CLIPS,
        DETECT_SHAKY,
        LABEL_SHAKY,
        ROUGH_CUT,
        DELETE_SHAKY,
        TRIM_TO_DURATION,
    }


@dataclass
class SLMCommand:
    """Structured representation of an SLM video editing command."""
    actions: List[str] = field(default_factory=list)
    parameters: Dict[str, Any] = field(default_factory=dict)
    raw_prompt: str = ""

    def has_action(self, action_name: str) -> bool:
        return action_name in self.actions

    def to_dict(self) -> Dict[str, Any]:
        data = {
            "actions": list(self.actions)
        }
        if self.parameters:
            data["parameters"] = self.parameters
        return data

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


class CommandSchemaValidator:
    """Validates and normalizes structured commands generated by SLM or NLP."""

    @staticmethod
    def validate_and_normalize(raw_data: Any, raw_prompt: str = "") -> SLMCommand:
        """
        Takes raw dictionary or JSON string from SLM and normalizes it into an SLMCommand.
        Safely handles malformed responses.
        """
        if isinstance(raw_data, str):
            try:
                # Find JSON block if response contains surrounding markdown or text
                text = raw_data.strip()
                if "```json" in text:
                    text = text.split("```json")[1].split("```")[0].strip()
                elif "```" in text:
                    text = text.split("```")[1].split("```")[0].strip()
                parsed = json.loads(text)
            except Exception as e:
                logger.warning(f"Failed to parse JSON string: {e}")
                parsed = {}
        elif isinstance(raw_data, dict):
            parsed = raw_data
        else:
            parsed = {}

        actions = []
        raw_actions = parsed.get("actions", [])

        if isinstance(raw_actions, list):
            for act in raw_actions:
                if isinstance(act, str):
                    clean_act = act.strip().lower()
                    # Normalize known action aliases
                    if clean_act in {"silence", "remove_silences", "silence_removal", "cut_silence"}:
                        clean_act = ActionType.REMOVE_SILENCE
                    elif clean_act in {"arrange", "reorder", "order_clips", "sort_clips", "arrange_timeline"}:
                        clean_act = ActionType.ARRANGE_CLIPS
                    elif clean_act in {"shaky", "find_shaky", "detect_shake", "detect_camera_shake"}:
                        clean_act = ActionType.DETECT_SHAKY
                    elif clean_act in {"label_shake", "mark_shaky", "tag_shaky", "indicate_shaky"}:
                        clean_act = ActionType.LABEL_SHAKY
                    elif clean_act in {"delete_shaky", "remove_shaky", "cut_shaky", "trim_shaky", "remove_shaky_parts", "remove_shaky_footage"}:
                        clean_act = ActionType.DELETE_SHAKY
                    elif clean_act in {"trim_to_duration", "trim_duration", "target_length"}:
                        clean_act = ActionType.TRIM_TO_DURATION
                    elif clean_act in {"roughcut", "make_rough_cut", "auto_cut"}:
                        clean_act = ActionType.ROUGH_CUT
                    
                    if clean_act in ActionType.ALL_ACTIONS and clean_act not in actions:
                        actions.append(clean_act)
                elif isinstance(act, dict):
                    # Handle object-style action: {"action": "remove_silence"}
                    action_name = act.get("action", "")
                    if action_name in ActionType.ALL_ACTIONS and action_name not in actions:
                        actions.append(action_name)

        # Logical inference: If user wants to label or delete shaky, they also need to detect shaky
        if ActionType.LABEL_SHAKY in actions and ActionType.DETECT_SHAKY not in actions:
            actions.insert(actions.index(ActionType.LABEL_SHAKY), ActionType.DETECT_SHAKY)
        if ActionType.DELETE_SHAKY in actions and ActionType.DETECT_SHAKY not in actions:
            actions.insert(actions.index(ActionType.DELETE_SHAKY), ActionType.DETECT_SHAKY)

        params = parsed.get("parameters", {})
        if not isinstance(params, dict):
            params = {}

        return SLMCommand(actions=actions, parameters=params, raw_prompt=raw_prompt)
