.TH LIBSMARTEDIT-AUDIO 1 "August 8, 2012" Linux "User Manuals"
.SH NAME
smartedit-audio-demo \- Display system info and play test sound

.SH SYNOPSIS
.B smartedit-audio-demo

.SH DESCRIPTION
Display information about detected audio interfaces, then play a test sound.
Uses the libsmartedit-audio library.

.TP
.B More information
 Project Website: http://www.smartedit.org/

.SH AUTHOR
libsmartedit was written by Jonathan Thomas <jonathan@smartedit.org>.

.PP
This manual page was written by Jonathan Thomas <jonathan@smartedit.org>,
for the Debian project (and may be used by others).
