#!/usr/bin/env python3

"""
 @file
 @brief This file is used to launch SmartEdit
 @author Jonathan Thomas <jonathan@smartedit.org>
 @author Noah Figg <eggmunkee@hotmail.com>

 @mainpage SmartEdit Video Editor 2.0

Welcome to the SmartEdit Video Editor 2.0 Qt documentation. SmartEdit was developed to
 make high-quality video editing and animation solutions freely available to the world. With a focus
 on stability, performance, and ease-of-use, we believe SmartEdit is the best cross-platform,
 open-source video editing application in the world!

 This documentation is auto-generated by Doxygen, using the doxypy Python filter. If you are
 interested in how SmartEdit Video Editor is designed, feel free to dive in, because this
 documentation was built just for you. If you are not a developer, please feel free to visit
 our main website (http://www.smartedit.org/download/), and download a copy today for Linux, Mac, or Windows.

 @section LICENSE

 Copyright (c) 2008-2018 SmartEdit Studios, LLC
 (http://www.smarteditstudios.com). This file is part of
 SmartEdit Video Editor (http://www.smartedit.org), an open-source project
 dedicated to delivering high quality video editing and animation solutions
 to the world.

 SmartEdit Video Editor is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 SmartEdit Video Editor is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with SmartEdit Library.  If not, see <http://www.gnu.org/licenses/>.
 """

import sys
import os
import argparse
import json
import logging
import traceback
import threading

def _smartedit_excepthook(exctype, value, tb):
    """Custom excepthook to log uncaught exceptions cleanly and prevent PyQt qFatal abort."""
    if issubclass(exctype, KeyboardInterrupt):
        sys.__excepthook__(exctype, value, tb)
        return
    formatted = "".join(traceback.format_exception(exctype, value, tb))
    msg = f"\nUnhandled Exception:\n{formatted}\n"
    try:
        sys.__stderr__.write(msg)
        sys.__stderr__.flush()
    except Exception:
        pass
    try:
        logging.getLogger("SmartEdit").error("Unhandled exception: %s", msg)
    except Exception:
        pass

sys.excepthook = _smartedit_excepthook
if hasattr(threading, "excepthook"):
    threading.excepthook = lambda args: _smartedit_excepthook(args.exc_type, args.exc_value, args.exc_traceback)


_src_dir = os.path.dirname(os.path.abspath(__file__))
if _src_dir not in sys.path:
    sys.path.insert(0, _src_dir)


if os.name == "nt":
    _msys_ucrt64 = r"C:\msys64\ucrt64\bin"
    if hasattr(os, "add_dll_directory"):
        for _d in (_src_dir, _msys_ucrt64):
            if os.path.isdir(_d):
                try:
                    os.add_dll_directory(_d)
                except Exception:
                    pass
    _exe_dir = os.path.dirname(os.path.abspath(sys.executable))
    _qt_dll_dirs = [
        os.path.join(_exe_dir, "lib", binding_name)
        for binding_name in ("PyQt{}".format(6), "PySide{}".format(6), "PyQt{}".format(5))
    ]
    _existing_qt_dll_dirs = [path for path in _qt_dll_dirs if os.path.isdir(path)]
    if _existing_qt_dll_dirs:
        os.environ["PATH"] = os.pathsep.join(_existing_qt_dll_dirs + [os.environ.get("PATH", "")])
        if hasattr(os, "add_dll_directory"):
            for _d in _existing_qt_dll_dirs:
                try:
                    os.add_dll_directory(_d)
                except Exception:
                    pass

if sys.platform != "win32":
    try:
        
        
        import smartedit
    except ImportError:
        pass


scale = 1.0
logger = logging.getLogger(__name__)

settings_path = os.path.join(os.path.expanduser("~/.smartedit_qt"), "smartedit.settings")

try:
    if os.path.exists(settings_path):
        with open(settings_path, "r", encoding="utf-8-sig") as fh:
            for item in json.load(fh):
                if item.get("setting") == "ui-scale":
                    scale = float(item.get("value", scale))
                    break
except Exception as exc:
    logger.warning("Failed to read UI scale from %s: %s", settings_path, exc, exc_info=True)
scale = max(0.5, min(3.0, scale))
if scale != 1.0:
    os.environ["QT_SCALE_FACTOR"] = str(scale)

from qt_api import QtCore, QtWidgets

Qt = QtCore.Qt
QApplication = QtWidgets.QApplication

try:
    
    QApplication.setAttribute(Qt.AA_ShareOpenGLContexts)
    from OpenGL import GL  
except (ImportError, AttributeError):
    pass

try:
    
    
    os.environ['QT_SCALE_FACTOR_ROUNDING_POLICY'] = "PassThrough"

    
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
except AttributeError:
    pass  

try:
    from classes import info
except ImportError:
    import smartedit_qt
    sys.path.append(smartedit_qt.SMARTEDIT_PATH)
    from classes import info


app = None


def main():
    """"Initialize settings (not implemented) and create main window/application."""

    global app

    
    parser = argparse.ArgumentParser(description='SmartEdit version ' + info.SETUP['version'])
    parser.add_argument(
        '-l', '--lang', action='store',
        help='language code for interface (overrides '
             'preferences and system environment)')
    parser.add_argument(
        '--list-languages', dest='list_languages',
        action='store_true',
        help='List all language codes supported by SmartEdit')
    parser.add_argument(
        '--path', dest='py_path', action='append',
        help='Additional locations to search for modules '
             '(PYTHONPATH). Can be used multiple times.')
    parser.add_argument(
        '--test-models', dest='modeltest',
        action='store_true',
        help="Load Qt's QAbstractItemModelTester into data models "
        '(requires Qt 5.11+)')
    parser.add_argument(
        '-d', '--debug', action='store_true',
        help='Enable debugging output')
    parser.add_argument(
        '--debug-file', action='store_true',
        help='Debugging output (logfile only)')
    parser.add_argument(
        '--debug-console', action='store_true',
        help='Debugging output (console only)')
    parser.add_argument('-V', '--version', action='store_true')
    parser.add_argument(
        'remain', nargs=argparse.REMAINDER, help=argparse.SUPPRESS)

    args, extra_args = parser.parse_known_args()

    
    if args.version:
        print(info.SETUP['version'])
        sys.exit()

    
    if args.debug or args.debug_file:
        info.LOG_LEVEL_FILE = 'DEBUG'
    if args.debug or args.debug_console:
        info.LOG_LEVEL_CONSOLE = 'DEBUG'

    if args.list_languages:
        from classes.language import get_all_languages
        print("Supported Languages:")
        for code, lang, country in get_all_languages():
            print("  {:>12}  {}".format(code, lang))
        sys.exit()

    if args.py_path:
        for p in args.py_path:
            newpath = os.path.realpath(p)
            try:
                if os.path.exists(newpath):
                    sys.path.insert(0, newpath)
                    print(f"Added {newpath} to PYTHONPATH")
                else:
                    print(f"{newpath} does not exist")
            except TypeError as ex:
                print(f"Bad path {newpath}: {ex}")
                continue

    if args.modeltest:
        info.MODEL_TEST = True
        
        if os.getenv('QT_LOGGING_RULES') is None:
            os.putenv('QT_LOGGING_RULES', 'qt.modeltest.debug=true')
    if args.lang:
        if args.lang in info.SUPPORTED_LANGUAGES:
            info.CMDLINE_LANGUAGE = args.lang
        else:
            print(f"Unsupported language '{args.lang}'! (See --list-languages)")
            sys.exit(-1)

    
    print(f"Loaded modules from: {info.PATH}")

    
    from classes import http_client, sentry
    http_client.configure_ssl_environment()

    
    sentry.init_tracing()

    
    info.setup_userdirs()

    
    from classes.app import SmartEditApp

    argv = [sys.argv[0]]
    argv.extend(extra_args)
    argv.extend(args.remain)
    try:
        app = SmartEditApp(argv)
    except Exception as ex:
        if app is not None:
            app.show_errors()
        else:
            print(f"Error initializing SmartEditApp: {ex}", file=sys.stderr)
            sys.exit(1)

    if not app:
        sys.exit(1)

    
    app.setApplicationName('smartedit')
    app.setApplicationVersion(info.VERSION)
    try:
        
        app.setDesktopFile("org.smartedit.SmartEdit")
    except AttributeError:
        pass

    
    if app.gui():
        if hasattr(app, "exec") and callable(app.exec):
            exit_code = app.exec()
        elif hasattr(app, "exec_") and callable(app.exec_):
            exit_code = app.exec_()
        else:
            raise AttributeError("SmartEditApp has no exec_/exec method")
        sys.exit(exit_code)


if __name__ == "__main__":
    main()
